ZumbieSolution/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            string nome = Request.QueryString["nome"];
            string nomeCategoria = Request.QueryString["nomeCategoria"];

            RecursoDao recursoDao = new RecursoDao();
            ViewBag.Recursos = recursoDao.BuscaPorNomeCategoriat(nome,nomeCategoria);



            CategoriaDao categoriaDao = new CategoriaDao();
            ViewBag.Categorias = categoriaDao.List();
            return View();
        }

        public ActionResult Novo()
        {
            return View();
        }
    }
}

ZumbieSolution/Controllers/ModalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;

namespace ZumbieSolution.Controllers
{
    public class ModalController : Controller
    {
        // GET: Modal
        public ActionResult Entrada()
        {
            UsuarioDao usuarioDao = new UsuarioDao();
            ViewBag.Usuarios = usuarioDao.List();
            return View();
        }
        public ActionResult Saida()
        {
            UsuarioDao usuarioDao = new UsuarioDao();
            ViewBag.Usuarios = usuarioDao.List();
            return View();
        }
    }
}

ZumbieSolution/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}


<form action="/" class="form-inline" method="get">
    <input type="text" name="nome" class="form-control input-sm" value="@Request.QueryString["nome"]" placeholder="Nome do Recurso" />
    <select name="nomeCategoria" class="form-control input-sm">
        <option value="">Todos</option>
        @foreach (var categoria in ViewBag.Categorias)
        {
            <option value="@categoria.Nome" selected="@categoria.Nome.Equals(@Request.QueryString["nomeCategoria"])">@categoria.Nome</option>
        }
    </select>

    <button type="submit" class="btn btn-success btn-sm">Busca</button>
</form>

<table class="table table-hover table-style text-center">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Quantidade</th>
            <th>Categoria</th>
            <th class="col-md-2">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var Recurso in ViewBag.Recursos)
        {
            <tr>
                <td>@Recurso.Nome</td>
                <td>@Recurso.Descricao </td>
                <td>@Recurso.QtdTotal</td>
                <td>@Recurso.Categoria.Nome</td>
                <td>
                    <button type="button" recursoId="@(Recurso.Id)" recursoNome="@(Recurso.Nome)" title="Novo recurso" class="btn btn-success btn-sm entrada"><i class="fa fa-plus" aria-hidden="true"></i> Entrada</button>
                    @if (@Recurso.QtdTotal > 0)
                    {
                        <button type="button" recursoId="@(Recurso.Id)" recursoNome="@(Recurso.Nome)" title="Saida de recurso"  class="btn btn-danger btn-sm saida"><i class="fa fa-minus" aria-hidden="true"></i> Saida</button>
                    }
                    else
                    {
                        <button type="button" title="Diminuir menos um na quantidade" class="btn btn-danger btn-sm disabled"><i class="fa fa-minus" aria-hidden="true"> Saida</i></button>
                    }
                </td>
            </tr>
        }
       
    </tbody>
</table>


@Html.Action("Entrada", "Modal");
@Html.Action("Saida", "Modal");

@section Scripts{
<script src="~/Content/js/Scripts.js"></script>
    
}