ZumbieSolution/Controllers/FuncaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class FuncaoController : Controller
    {
        // GET: Funcao
        public ActionResult Index()
        {
            FuncaoDao funcaoDao = new FuncaoDao();
            ViewBag.Funcoes = funcaoDao.List();
            return View();
        }

        public ActionResult Novo(int id = 0)
        {
            Funcao funcao;
            if (id.Equals(null) || id.Equals(0))
            {
                funcao = new Funcao();
            }
            else
            {
                FuncaoDao dao = new FuncaoDao();
                funcao = dao.Find(id);
            }
            ViewBag.Funcao = funcao;
            return View();
        }

        public ActionResult Cadastro(Funcao funcao)
        {
            FuncaoDao funcaoDao = new FuncaoDao();
            if (funcao.Id.Equals(null) || funcao.Id.Equals(0))
            {
                funcaoDao.Insert(funcao);
            }
            else
            {
                funcaoDao.Update(funcao);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            FuncaoDao dao = new FuncaoDao();
            dao.DeleteById(id);
            return Json(id);
        }
    }
}

ZumbieSolution/Controllers/MovimentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class MovimentacaoController : Controller
    {
        // GET: Movimentacao
        public ActionResult Entrada(Re_entrada entrada)
        {
            MovimentacaoDao dao = new MovimentacaoDao();
            entrada.Data = DateTime.Now;
            dao.Entrada(entrada);
            return RedirectToAction("Index","Home");
        }

        public ActionResult saida(Re_saida saida)
        {
            MovimentacaoDao dao = new MovimentacaoDao();
            saida.Data = DateTime.Now;
            dao.Saida(saida);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Entradas()
        {
            MovimentacaoDao dao = new MovimentacaoDao();
            ViewBag.Entradas = dao.EntradaList();
            return View();
        }

        public ActionResult Saidas()
        {
            MovimentacaoDao dao = new MovimentacaoDao();
            ViewBag.Saidas = dao.SaidaList();
            return View();
        }
    }
}

ZumbieSolution/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class UsuarioController : Controller
    {
         public ActionResult Index()
        {
            UsuarioDao usuarioDao = new UsuarioDao();
            ViewBag.Usuarios = usuarioDao.List();
            return View();
        }

        public ActionResult Novo(int id = 0)
        {
            Usuario usuario;
            if (id.Equals(null) || id.Equals(0))
            {
                usuario = new Usuario();
            }
            else
            {
                UsuarioDao dao = new UsuarioDao();
                usuario = dao.Find(id);
            }
            FuncaoDao funcaoDao = new FuncaoDao();

            ViewBag.Funcoes = funcaoDao.List();
            ViewBag.Usuario = usuario;
            return View();
        }

        public ActionResult Cadastro(Usuario usuario)
        {
            UsuarioDao usuarioDao = new UsuarioDao();
            if (usuario.Id.Equals(null) || usuario.Id.Equals(0))
            {
                usuarioDao.Insert(usuario);
            }
            else
            {
                usuarioDao.Update(usuario);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            UsuarioDao dao = new UsuarioDao();
            dao.DeleteById(id);
            return Json(id);
        }
    }
}

ZumbieSolution/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/css/sweetalert.css" rel="stylesheet" />

    <script src="~/Content/js/jquery-3.2.1.min.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/sweetalert.min.js"></script>

    <title>@ViewBag.Title</title>

    <style>
        .navbar {
            border-radius: 0 !important;
        }

            .navbar li > a:hover {
                background-color: #080808 !important;
                color: #ffffff !important;
            }
    </style>
</head>
<body>
    @Html.Partial("_MenuSuperior")

    @RenderBody()


    @RenderSection("Scripts", required: false)

</body>
</html>

ZumbieSolution/Views/Shared/_MenuSuperior.cshtml
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/Home">Stoque</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Recurso", "Index", "Recurso")</li>
                <li>@Html.ActionLink("Categoria", "Index", "Categoria")</li>
                <li>@Html.ActionLink("Função", "Index", "Funcao")</li>
                <li>@Html.ActionLink("Usuários", "Index", "Usuario")</li>
                <li>@Html.ActionLink("Entradas", "Entradas", "Movimentacao")</li>
                <li>@Html.ActionLink("Saidas", "Saidas", "Movimentacao")</li>
            </ul>
        </div>

    </div>
</div>