ZumbieSolution/Models/Recurso.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ZumbieSolution.Models
{
    public class Recurso
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public int QtdTotal { get; set; }
        public virtual Categoria Categoria { get; set; }
        public int CategoriaId { get; set; }
        public string Descricao { get; set; }

        
    }
}

ZumbieSolution/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class CategoriaController : Controller
    {
        // GET: Categoria
        public ActionResult Index()
        {
            CategoriaDao categoriaDao = new CategoriaDao();
            ViewBag.Categorias = categoriaDao.List();
            return View();
        }

        public ActionResult Novo(int id =0)
        {
            Categoria categoria;
            if (id.Equals(null) || id.Equals(0))
            {
                categoria = new Categoria();
            }
            else
            {
                CategoriaDao dao = new CategoriaDao();
                categoria = dao.Find(id);
            }
            ViewBag.Categoria = categoria;
            return View();
        }

        public ActionResult Cadastro(Categoria categoria)
        {
            CategoriaDao categoriaDao = new CategoriaDao();
            if (categoria.Id.Equals(null) || categoria.Id.Equals(0))
            {
                categoriaDao.Insert(categoria);
            }
            else
            {
                categoriaDao.Update(categoria);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            CategoriaDao dao = new CategoriaDao();
            dao.DeleteById(id);
            return Json(id);
        }

    }
}

ZumbieSolution/Controllers/RecursoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZumbieSolution.DAO;
using ZumbieSolution.Models;

namespace ZumbieSolution.Controllers
{
    public class RecursoController : Controller
    {
        // GET: Recurso
        public ActionResult Index()
        {
            RecursoDao recursoDao = new RecursoDao();
            ViewBag.Recursos = recursoDao.List();
            return View();
        }

        public ActionResult Novo(int id = 0)
        {
            Recurso recurso;
            if (id.Equals(null) || id.Equals(0))
            {
                recurso = new Recurso();
            }
            else
            {
                RecursoDao dao = new RecursoDao();
                recurso = dao.Find(id);
            }
            CategoriaDao categoriaDao = new CategoriaDao();
            ViewBag.Categorias = categoriaDao.List();
            ViewBag.Recurso = recurso;
            return View();
        }

        public ActionResult Cadastro(Recurso recurso)
        {
            RecursoDao recursoDao = new RecursoDao();
            if (recurso.Id.Equals(null) || recurso.Id.Equals(0))
            {
                recursoDao.Insert(recurso);
            }
            else
            {
                recursoDao.Update(recurso);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            RecursoDao dao = new RecursoDao();
            dao.DeleteById(id);
            return Json(id);
        }
    }
}

ZumbieSolution/Views/Recurso/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<a href="@Url.Action("Novo","Recurso")" class="btn btn-sm btn-success pull-right">Adicionar</a>

<table class="table table-hover table-style text-center">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Categoria</th>
            <th class="col-md-1">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var recurso in ViewBag.Recursos)
        {
            <tr id="tr@(recurso.Id)">
                <td>@recurso.Nome</td>
                <td>@recurso.Descricao </td>
                <td>@recurso.Categoria.Nome </td>
                <td>
                    <a href="@Url.Action("Novo","Recurso",new { recurso.Id })" class="btn btn-success btn-sm" title="Ediatr"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                    <button type="button" title="Excluir" onclick="deleteTr(@(recurso.Id))" class="btn btn-danger btn-sm"><i class="fa fa-trash" aria-hidden="true"></i></button>
                </td>
            </tr>
        }

    </tbody>
</table>

<script>

    function deleteTr(id) {
        swal({
            title: "Você tem certeza?",
            text: "Você tem certeza que deseja fazer essa alteração!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Sim",
            cancelButtonText: "Não",
            closeOnConfirm: false,
            closeOnCancel: false
        },
            function (isConfirm) {
                if (isConfirm) {

                    $.ajax({
                        type: "post",
                        url: "@Url.Action("Remove", "Recurso")",
                        data: { id: id },
                        success: function (data) {
                            $("#tr" + data).remove();
                            swal("Deletado!", "Operação realizada com sucesso.", "success");
                        },
                        error: function (data) {
                            console.log(data);
                            swal("Erro", "Erro ao tenta excluir:" + data, "error");
                        }

                    });
                } else {
                    swal("Cancelado", "Operação realizada com sucesso.", "error");
                }
            });

    }
</script>

ZumbieSolution/Views/Recurso/Novo.cshtml
@{
    ViewBag.Title = "Cadastro";
}

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form action="@Url.Action("Cadastro","Recurso")" method="post">
            <h3 class="text-center">Cadastro de Recurso</h3>
            <input type="hidden" name="recurso.Id" value="@ViewBag.recurso.Id" />
            <div class="form-group col-md-6">
                <label for="recurso.Nome">Nome</label>
                <input type="text" name="recurso.Nome" value="@ViewBag.recurso.Nome" class="form-control input-sm" required/>
            </div>

            <div class="form-group col-md-6">
                <label for="recurso.Descricao">Descrição</label>
                <input type="text" name="recurso.Descricao" value="@ViewBag.recurso.Descricao" class="form-control input-sm" required/>
            </div>

            <div class="form-group col-md-6">
                <label for="recurso.Categoria.Id">Categoria: </label>
                <a href="@Url.Action("Novo","Categoria")">Nova Categoria</a>
                <select class="form-control input-sm" name="recurso.Categoria.Id" required>
                    @foreach (var categoria in ViewBag.Categorias)
                    {
                        <option value="@categoria.Id" selected="@categoria.Id.Equals(ViewBag.Recurso.CategoriaId)">@categoria.Nome</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <p class="pull-right">
                    <button class="btn btn-sm btn-success">Salvar</button>
                </p>
            </div>
        </form>
    </div>
</div>